# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d06c4d273680dff40f19b178e38e66a22b80203829636afc7b57935b5d4909b30bf7a0488e5221bdb9f487ac5afa0ef506db3f41b206be4beb4b45cc92aa7baa

test:
  secret_key_base: 8eb573e555ce7c90cfae1be33433be3e05cc42663ba34b6a94e7620181911999d1359eecd9add4cd70c76396aa526ae68688497e54883b4d4c3feaae0a910385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
